version: '3.7'

services:
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  db:
    restart: always
    image: mysql:5.7
    container_name: "db"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: ${DATABASE_HOST}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    container_name: "web"
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
      - redis
    networks:
      - default

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    networks:
      - default
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

volumes:
  mysql:
    driver: local
  redis:
    driver: local