# GitHub Action for Golang
name: API
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.13' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go run hello.go # Run lint, generate, build and test
#  deploy-dev:
#    runs-on: ubuntu-latest
#    needs: laravel
#    if: github.ref == 'refs/heads/develop'
#    steps:
#      - name: Deploy the Go Application
#        run: curl --location --request POST
#  deploy-prod:
#    runs-on: ubuntu-latest
#    needs: laravel
#    if: github.ref == 'refs/heads/master'
#    steps:
#      - name: Deploy the Go Application
#        run: curl --location --request POST